

services:
 
  db:
    image: postgres:13
    container_name: tedarikci_db
    environment:
      - POSTGRES_USER=kullanici
      - POSTGRES_PASSWORD=sifre
      - POSTGRES_DB=tedarikci_app
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  web:
    build:
      context: ./flask_app
      dockerfile: dockerfile.dev
  
    container_name: insight_engine_web # Projemizin ismini kullanalım
    
    ports:
      - "5005:5001"
      
    environment:
      - POSTGRES_USER=kullanici
      - POSTGRES_PASSWORD=sifre
      - POSTGRES_DB=tedarikci_app
      
 
    depends_on:
      - db
